### ISSUE TITLE
Diff command strictly compares files vs database values, resulting in incorrect diffs

### ISSUE THREAD

**Issue by punkstar** [punkstar/mageconfigsync#7]
In this example, the following YAML file was used:

```
default:
        system/smtp/disable: 1
```

Then this command was run:

```
$ bin/mageconfigsync diff --magento-root public/ etc/mageconfigsync.yml
default/system/smtp/disable is different (File: '1', DB: '1')
default/scene/general/proxy_enabled is different (File: '0', DB: '0')
```

**Comment by benn-be** [comment]
I don't know if that is related but :

    default:
        admin/security/password_lifetime: null

With this command run :

    $ bin/mageconfigsync diff --magento-root public/ etc/mageconfigsync.yml
    default/admin/security/password_lifetime is different (File: null, DB: null)

**Comment by davidselo** [comment]
Good Afternoon, 

I am testing the tool and I am having the same issue. Are there any updates on this issue? Is there any plan to fix this issue in the near future or in a new version? 

Thanks in advance,
David
